# Generated by Django 4.2.7 on 2025-07-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
